accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# le paramètre name est utilisé comme référence dans le href des url des pages selon {% url 'home' %}...
# path('Nom de chemain à taper dans la barre d'url de browser',Nom de chemain à traverser en backend par les href des links)

app_name = 'accounts'

urlpatterns = [
        path('signup',views.signup,name='signup'),
        path('profile',views.profile,name='profile'),
        path('profile/',views.adminProfile,name='admin_profile'),
        path('profile/edit',views.profile_edit,name='profile_edit'),
]

lang/urls.py
from django.urls import path
from . import views

app_name = 'lang'

urlpatterns = [
    path('acceuil',views.acceuil,name='acceuil'),
]

simulator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

#to change language
urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),

]

urlpatterns += i18n_patterns (
    path('accounts/', include('django.contrib.auth.urls')),# Add Django site authentication urls (for login, logout, password management)
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),
    path('admin/', admin.site.urls),
    path('',include('professeurs.urls')),#include pour toutes les urls de l'application professeurs
    path('',include('lang.urls',namespace='lang')),
    path('',include('django.contrib.auth.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.ForeignKey('City',related_name='user_city',max_length=100,on_delete=models.CASCADE,blank=True,null=True,default="")
    phone_number = models.CharField(max_length=15)
    image = models.ImageField(upload_to='profile/%Y/%m/%d/',null=True,blank=True)
    
    def __str__(self):
        return str(self.user)



@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        
class City(models.Model):
    name = models.CharField(max_length=30)    

    def __str__(self):
        return str(self.name)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.contrib.auth.models import User
from django import forms
from .models import Profile
# Implementation of class for creating forms:

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username","email","password1","password2"]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city','phone_number','image']

accounts/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm , UserForm,ProfileForm
from django.contrib.auth import authenticate, login
from .models import Profile
from django.urls import reverse
# Create your views here.

def signup(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            #importer le username et le password depuis le form et le stoker dans les variables
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username,password=password) # Django vérifie si le user qui se log est le même enregistré dans la base de donné (il est entrain de lui authentifier)
            login(request,user) 
            return redirect('/accounts/profile')
    else : 
        form = RegisterForm()         
    return render(request,'registration/signup.html',{'form':form})



def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})


def adminProfile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/admin_profile.html',{'profile':profile})


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        userform = UserForm(request.POST,instance=request.user) 
        profileform = ProfileForm(request.POST,request.FILES,instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile = profileform.save(commit=False)
            myprofile.user = request.user
            myprofile.save()
            return redirect(reverse('accounts:profile'))
    else :
        userform = UserForm(instance=request.user) 
        profileform = ProfileForm(instance=profile)
    return render(request,'accounts/profile_edit.html',{'userform':userform , 'profileform':profileform})

accounts/templates/accounts/admin_profile.html
{% include 'base.html' %}
{% include 'navigation.html' %}

{% block content %}

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
    {% else %}
      <p>Please login to see this page.</p>
    {% endif %}
  {% endif %}

<style>
  .mydivstyle:hover {
     box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.3);
     transform: translateY(-20px) ;
  }
</style>


<section class="bg-dark text-center py-9">
    <div class="container bg-light p-4" style="border: 2px solid rgb(48, 73, 186); border-radius: 12px;">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
            <ol class="breadcrumb mb-0">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="">User</a></li>
              <li class="breadcrumb-item"><a href="{% url 'form2' %}">Simulation de la paie</a></li>
              <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}">User Profile</a></li>
            </ol>
          </nav>
        </div>
      </div>
  
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
              <img src="{{profile.image.url}}" alt="{{user.username}}'s profile image"
                        class="rounded img-fluid" style="width: 150px;">
              <h5 class="my-3 text-dark">{{profile}}</h5>
              <p class="text-muted mb-1">Full Stack Developer</p>
              <p class="text-muted mb-4">{{profile.city}}</p>
              <div class="d-flex justify-content-center mb-2">
                <button type="button" class="btn btn-primary">Follow</button>
                <button type="button" class="btn btn-outline-primary ms-1">Message</button>
              </div>
            </div>
          </div>

          <div class="card mb-4 mb-lg-0">
            <div class="card-body p-0">
              <ul class="list-group list-group-flush rounded-3">
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fas fa-globe fa-lg text-warning"></i>
                  <p class="mb-0 text-info">Globe</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                  <p class="mb-0 text-info">Github</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                  <p class="mb-0 text-info">Twitter</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                  <p class="mb-0 text-info">Instagram</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                  <p class="mb-0 text-info">Facebook</p>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">User Name : </p>
                </div>
                <div class="col-sm-9">
                  <p class="mb-0 text-info">{{profile}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">First Name : </p>
                </div>
                <div class="col-sm-9">
                  <p class=" mb-0 text-info">{{profile.user.first_name}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Last Name : </p>
                </div>
                <div class="col-sm-9">
                  <p class="mb-0 text-info">{{profile.user.last_name}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email : </p>
                </div>
                <div class="col-sm-9">
                  <p class="mb-0 text-info">{{profile.user.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">City : </p>
                </div>
                <div class="col-sm-9">
                  <p class="mb-0 text-info">{{profile.city}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone : </p>
                </div>
                <div class="col-sm-9">
                  <p class="mb-0 text-info">{{profile.phone_number}}</p>
                </div>
              </div>
              <hr>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                  </p>
                  <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                  <div class="progress rounded mb-2" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
                <div class="card mb-4 mb-md-0">
                        <div class="card-body">
                        <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                        </p>
                        <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                        <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                        <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                        <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                        <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                        <div class="progress rounded mb-2" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        </div>
                </div>
            </div>
            <div class="d-flex justify-content-center mb-2 my-5">
                <button type="button" class="btn btn-primary "><a href="{% url 'accounts:profile_edit' %}" class="text-reset">Edit Profile</a></button>
              </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <style>
    .form-special input, .form-special select {
        border-radius: 7px;
        padding: 8px;
        appearance: auto;
    }
</style>

{% endblock content %}
{% include 'footer.html' %}

accounts/templates/accounts/profile.html
{% include 'base.html' %}
{% include 'navigation.html' %}

{% load i18n %}

{% block content %}

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
    {% else %}
      <p>Please login to see this page.</p>
    {% endif %}
  {% endif %}

<style>
  .mydivstyle:hover {
     box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.3);
     transform: translateY(-20px) ;
  }
</style>


<section class="bg-dark text-center py-9">
    <div class="container bg-light p-4" style="border: 2px solid rgb(48, 73, 186); border-radius: 12px;">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
            <ol class="breadcrumb mb-0">
              <li class="breadcrumb-item"><a href="#"> {% trans "Home" %} </a></li>
              <li class="breadcrumb-item"><a href=""> {% trans "User"  %} </a></li>
              <li class="breadcrumb-item"><a href="{% url 'form2' %}"> {% trans "Simulation de la paie" %} </a></li>
              <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}"> {% trans "User Profile" %} </a></li>
            </ol>
          </nav>
        </div>
      </div>
  
         <div class="row">
            <div class="col-lg-4">
                  <div class="card mb-4">
                    <div class="card-body text-center">
                      <img src="{{profile.image.url}}" alt="{{user.username}}'s profile image"
                        class="rounded img-fluid" style="width: 150px;">
                      <h5 class="my-3 text-dark">{{profile}}</h5>
                      <p class="text-muted mb-1"> {% trans "Full Stack Developer" %} </p>
                      <p class="text-muted mb-4">{{profile.city}}</p>
                      <div class="d-flex justify-content-center mb-2">
                        <button type="button" class="btn btn-primary"> {% trans "Follow" %} </button>
                        <button type="button" class="btn btn-outline-primary ms-1">Message</button>
                    </div>
              </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body p-0">
              <ul class="list-group list-group-flush rounded-3">
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fas fa-globe fa-lg text-warning"></i>
                  <p class="mb-0 text-info">Globe</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                  <p class="mb-0 text-info">Github</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                  <p class="mb-0 text-info">Twitter</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                  <p class="mb-0 text-info">Instagram</p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                  <p class="mb-0 text-info">Facebook</p>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">User Name : </p>
                </div>
                <div class="col-sm-9">
                  <p class="mb-0 text-info">{{profile}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">First Name : </p>
                </div>
                <div class="col-sm-9">
                  <p class="text-info mb-0">{{profile.user.first_name}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Last Name : </p>
                </div>
                <div class="col-sm-9">
                  <p class="text-info mb-0">{{profile.user.last_name}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email : </p>
                </div>
                <div class="col-sm-9">
                  <p class="text-info mb-0">{{profile.user.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">City : </p>
                </div>
                <div class="col-sm-9">
                  <p class="text-info mb-0">{{profile.city}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Phone : </p>
                </div>
                <div class="col-sm-9">
                  <p class="text-info mb-0">{{profile.phone_number}}</p>
                </div>
              </div>
              <hr>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                  </p>
                  <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                  <div class="progress rounded mb-2" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
                <div class="card mb-4 mb-md-0">
                        <div class="card-body">
                        <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
                        </p>
                        <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                        <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
                        <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
                        <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
                        <div class="progress rounded" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
                        <div class="progress rounded mb-2" style="height: 5px;">
                            <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                            aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        </div>
                </div>
            </div>
            <div class="d-flex justify-content-center mb-2 my-5">
                <button type="button" class="btn btn-primary "><a href="{% url 'accounts:profile_edit' %}" class="text-reset">Edit Profile</a></button>
              </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <style>
    .form-special input, .form-special select {
        border-radius: 7px;
        padding: 8px;
        appearance: auto;
    }
</style>

{% endblock content %}
{% include 'footer.html' %}