accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# le paramètre name est utilisé comme référence dans le href des url des pages selon {% url 'home' %}...
# path('Nom de chemain à taper dans la barre d'url de browser',Nom de chemain à traverser en backend par les href des links)

app_name = 'accounts'

urlpatterns = [
        path('signup',views.signup,name='signup'),
        path('profile',views.profile,name='profile'),
        path('profile/',views.adminProfile,name='admin_profile'),
        path('profile/edit',views.profile_edit,name='profile_edit'),
]

contact/urls.py
from django.urls import path
from . import views

# le paramètre name est utilisé comme référence dans le href des url des pages selon {% url 'home' %}...
# path('Nom de chemain à taper dans la barre d'url de browser',Nom de chemain à traverser en backend par les href des links)

app_name = 'contact'

urlpatterns = [
        path('contact-us/',views.send_message,name='contact-us'),
]

lang/urls.py
from django.urls import path
from . import views

app_name = 'lang'

urlpatterns = [
    path('acceuil',views.acceuil,name='acceuil'),
]

professeurs/urls.py
from django.contrib import admin
from django.urls import path
from .views import About,Home,Blogs,Texte,Index,Form,Afficher_resultats_calculs,combined_data_view,selected_data_view,liberubr_list_view,generate_pdf #userLogin

# le paramètre name est utilisé comme référence dans le href des url des pages selon {% url 'home' %}...
# path('Nom de chemain à taper dans la barre d'url de browser',Nom de chemain à traverser en backend par les href des links)

urlpatterns = [
    path('', Home,name='home'),
    path('about/', About,name='about'),
    #path('login/',userLogin,name='login'),
    path('blogs/',Blogs,name='blogs'),      
    path('texte/',Texte,name='texte'),
    path('index/',Index,name='dashboard'),
    path('form2/',Form,name='form2'),
    path('result/',Afficher_resultats_calculs,name='result'),
    path('combined-data/', combined_data_view, name='combined-data'),
    path('selected-data/',selected_data_view, name='selected-data'),
    path('liberubr-list/',liberubr_list_view, name='liberubr-list'),
    path('generate-pdf/', generate_pdf, name='generate_pdf'),
]

simulator/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

#to change language
urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),

]

urlpatterns += i18n_patterns (
    path('accounts/', include('django.contrib.auth.urls')),# Add Django site authentication urls (for login, logout, password management)
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),
    path('admin/', admin.site.urls),
    path('',include('professeurs.urls')),#include pour toutes les urls de l'application professeurs
    path('',include('lang.urls',namespace='lang')),
    path('',include('django.contrib.auth.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.


class Info(models.Model):
    place = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=255)

    class Meta:
        verbose_name = ("Info")
        verbose_name_plural = ("Infos")

    def __str__(self):
        return self.email    
    

contact/views.py
from django.shortcuts import render
from .models import Info
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.

def send_message(request):
    myinfo = Info.objects.first()

    if request.method == 'POST':
        subject = request.POST.get('subject', '')  # Safely get subject with default value ''
        email = request.POST.get('email', '')
        message = request.POST.get('message', '')

        send_mail(
            subject,
            message ,
            settings.EMAIL_HOST_USER,
            [email],
        )

    return render(request,'contact/contact.html',{'myinfo':myinfo})

professeurs/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import Professeur,SitPaieProfEnsSec2Gr,RubDroitProfEnsSec2Gr,ListeFamilleGrade,ListeGrade
from .forms import ProfesseurForm,MonFormulaireDjango,SitPaieProfForm  
from django.views.generic import ListView, DetailView, CreateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import psycopg2
from django.db.models import Sum
from django.urls import reverse
import os
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

# Create your views here.


def About(request):
    return render(request,'about.html')

def Home(request):
    return render(request,'home.html')



def Index(request):
    if not request.user.is_staff:
        return redirect('login')
    return render(request,'index.html')



def Blogs(request):
    return render(request,'blogs.html')

def Texte(request):
    return render(request,'texte.html')

def Form (request):
    if request.method == 'POST': #Pour des raison de sécurité
        form = ProfesseurForm(request.POST)
        if form.is_valid():#ne pas enregistrer ssi les informations sont valide (eviter les attack js)
            form.save()
            # Optionally, you can add a success message or redirect to another page
            # return redirect('success_page')
    else:
        form = ProfesseurForm()

    return render(request, 'form.html', {'form': form})


"""def create_professeur(request):
    if request.method == 'POST':
        form = ProfesseurForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_page')  # Redirect to a success page after saving the data.
    else:
        form = ProfesseurForm()
    
    return render(request, 'form.html', {'form': form})"""


def ma_vue(request):
    if request.method == 'POST':
        form = MonFormulaireDjango(request.POST)
        if form.is_valid():
            # Handle form submission here
            return render(request, 'success_page.html')
    else:
        form = MonFormulaireDjango()

    return render(request, 'form.html', {'form': form})


"""def Test(request):
    data = ProfesseurForm(request.POST)
    data.save()"""
"""categorie = request.POST.get('categorie')
    corps = request.POST.get('corps')
    cadre = request.POST.get('cadre')
    grade = request.POST.get('grade')
    #indice = request.POST.get('indice')
    region = request.POST.get('region')
    mutuelle = request.POST.get('mutuelle')
    #marie = request.POST.get('marie')
    nombre_enfants = request.POST.get('nombre_enfant')
    data = Professeur(categorie=categorie,corps=corps,cadre=cadre,grade=grade,region=region,mutuelle=mutuelle,nombre_enfants=nombre_enfants)"""
     
"""return render(request,'test.html' , {'key_test':ProfesseurForm})"""

"""def Test(request):
    if request.method == 'POST': #Pour des raison de sécurité
        form = ProfesseurForm(request.POST)
        if form.is_valid():#ne pas enregistrer ssi les informations sont valide (eviter les attack js)
            form.save()
            # Optionally, you can add a success message or redirect to another page
            # return redirect('success_page')
    else:
        form = ProfesseurForm()

    return render(request, 'test.html', {'form': form})"""

def Afficher_resultats_calculs(request):
    # Récupérer toutes les instances de Professeur ou les instances nécessaires selon vos besoins
    professeurs = Professeur.objects.all()
    
    # Effectuer les calculs pour chaque instance de professeur
    for professeur in professeurs:
        professeur.traitement_base_calcul = professeur.calculer_traitement_base()
        professeur.indemnite_residence_calcul = professeur.calculer_indemnite_residence()
        professeur.total_calcul_indemnites = professeur.calculer_total_indemnites()
        professeur.allocation_calcul_familial= professeur.calculer_allocation_familiale()
        professeur.indemnite_calcul_encadrement= professeur.calculer_indemnite_encadrement()
        professeur.indemnite_recherche_applicue_calculer= professeur.calculer_indemnite_recherche_appliquee()
        professeur.indemnite_calcule_risque= professeur.calculer_indemnite_risque()
        professeur.total_calcule_indemnites= professeur.calculer_total_indemnites()
        professeur.total_calculer_mensuel_brut= professeur.calculer_total_mensuel_brut()
        professeur.cotisation_calcule_mutuelle= professeur.calculer_cotisation_mutuelle()
        professeur.cotisation_calcul_amo= professeur.calculer_cotisation_amo()
        professeur.calcul_sm_cotisation= professeur.calculer_cotisation_sm()
        professeur.calcul_cdd_cotisation= professeur.calculer_cotisation_ccd()
        professeur.total_calculer_cotisation= professeur.calculer_total_cotisations()
        professeur.impot_calcule_revenu= professeur.calculer_impot_revenu()
        professeur.salaire_calcule_brut= professeur.calculer_salaire_brut()
        professeur.net_calculer_imposable= professeur.calculer_net_imposable()
        professeur.total_calcule_revenu= professeur.calculer_total_revenus()
        professeur.salaire_net_calcule= professeur.calculer_salaire_net()
        professeur.frais_calculer_professionnels= professeur.calculer_frais_professionnels()

    # Passer les instances de professeur avec les résultats des calculs à la template
    context = {
        'professeurs': professeurs,
    }

    return render(request,'result.html', context)

## -- Authentification : -- ##



'''def userLogin(request):
    if request.method == "POST":
      form = LoginForm()
      inUsername = request.POST.get('username')
      inpPassword = request.POST.get('password')
      user = authenticate(request,username=inUsername, password=inpPassword)
      if user is not None: #si la variable user n'est pas null , None en django indique null . Donc si la variable contienne des données
         login(request,user)
         return redirect('professeurs:form2')
    else:
        form = LoginForm() #Sinon retourner le forme de login lui même
    return render(request,'login.html',{'form':form}) # render le contexte {'form':form} dans login.html'''


'''def recherche_rubrique(request):
    form = RechercheRubriqueForm()  # Create an instance of the form
    if request.method == 'POST':
        form = RechercheRubriqueForm(request.POST)  # Bind form data to the POST data
        if form.is_valid():
            libele_categorie = request.POST['libele_categorie']
            code_corp = request.POST['code_corp']
            code_cadre = request.POST['code_cadre']
            id_grade = request.POST['id_grade']
            code_grade = request.POST['code_grade']
            libele_grade = request.POST['libele_grade']
            code_comp = request.POST['code_comp']
            code_famgr = request.POST['code_famgr']
            echelle = request.POST['echelle']
            poinindi = request.POST['poinindi']

        try:
            rubrique = SitPaieProfEnsSec2Gr.objects.get(
                libele_catégorie=libele_categorie,
                code_corp=code_corp,
                code_cadre=code_cadre,
                id_grade=id_grade,
                libele_grade=libele_grade,
                code_comp=code_comp,
                code_famgr=code_famgr,
                echelle=echelle,
                poinindi=poinindi,
            )

            rubriques = [
                {
                    'libele_rubrique': rubrique.libele_rubrique,
                    'montant_mensuel': rubrique.montant_octr / 12,
                }
            ]
        except SitPaieProfEnsSec2Gr.DoesNotExist:
            conn = psycopg2.connect(
                dbname="simulateur",
                user="root",
                password="ilyass@123",
                host="127.0.0.1",
                port="5432"
            )
            cursor = conn.cursor()

            query = """
                        SELECT
                            sp.liberubr,
                            sp.montoctr / 12 AS montant_mensuel
                        FROM
                            "sit_paie_prof_ens_sec_2_gr" sp
                        JOIN
                            "rub_droit_prof_ens_sec_2_gr" rd1
                            ON sp.coderubr = rd1.coderubr
                        JOIN
                            "liste_grade_famille_grade" gf
                            ON sp.codfamgr = gf.codfamgr
                        JOIN
                            "liste_famille_grade" fg
                            ON gf.codfamgr = fg.codfamgr
                        JOIN
                            "liste_grade" lg
                            ON sp.idengrad = lg.idengrad
                        WHERE
                            sp.idengrad = %s
                            AND sp.codfamgr = %s
                            AND sp.libegrad = %s
                            AND sp.coderubr = %s
                    """

            cursor.execute(query, (
                    libele_categorie, code_corp, code_cadre, id_grade, code_grade, libele_grade, code_comp, code_famgr, echelle, poinindi
                ))
            results = cursor.fetchall()

            conn.close()

            rubriques = []
            for row in results:
                    rubrique = {
                        'libele_rubrique': row[0],
                        'montant_mensuel': row[1]
                    }
                    rubriques.append(rubrique)

        return render(request, 'resultats.html', {'rubriques': rubriques})

    else:
        form = RechercheRubriqueForm()

    return render(request, 'form.html', {'form': form})
'''

'''def data_view(request):

professeurs/templates/about.html
{% include 'base.html' %}
{% include 'navigation.html' %}


{% block content %}
<!-- ============================================-->
<!-- =============<section> begin ===============-->
        <section class="bg-dark text-center py-9">
         
          <div class="container">
            <p class="text-light fs-1">About</p>
            <div class="col-12 col-md-7 mx-auto">
              <h1 class="text-white fs-lg-7 fs-md-4 fs-3 my-4">Nous cherchon toujours à vous créer une solution qui répond à vos besoin</h1>
            </div>
            <p class="w-md-50 text-light mx-auto">Chez nous, chaque client est une priorité inestimable. Votre satisfaction et vos besoins sont au cœur de tout ce que nous faisons. Votre confiance en notre entreprise nous inspire à continuellement nous améliorer et à vous offrir des solutions exceptionnelles qui répondent parfaitement à vos attentes</p>
          </div>
          <!-- end of .container-->
  
        </section>
        
      <section class="pb-0 bg-light">
  
          <div class="container">
            <div class="gallery-wraper">
              {% load static %}
              <div class="img-wraper"><img class="img-fluid" src="{% static 'assets/img/gallery/1.png' %}" alt="" /></div>
              <div class="img-wraper"><img class="img-fluid" src="{% static 'assets/img/gallery/2.png' %}" alt="" /></div>
              <div class="img-wraper"><img class="img-fluid" src="{% static 'assets/img/gallery/3.png' %}" alt="" /></div>
              <div class="img-wraper"><img class="img-fluid" src="{% static 'assets/img/gallery/4.png' %}" alt="" /></div>
              <div class="img-wraper"><img class="img-fluid" src="{% static 'assets/img/gallery/5.png' %}" alt="" /></div>
            </div>
            
            <div class="px-xl-8 px-md-5 px-3 py-8">
              <i class="bi bi-patch-question-fill"></i><p class="fs-1">question</p>
              <h1 class="fs-lg-6 fs-md-4 fs-3 my-4">Pourquoi créer un simulateur de la paie</h1>
              <p class="fs-1">La solution de simulation de la paie offre des avantages indéniables aux corps qui ont besoin de cette information pour leur gestion ou leur organisation. En effet, la simulation est un moyen de prévoir les montants à payer d’une part, et les résultats de la simulation constituent des outils de prise de décision à ne pas négliger d’autre part.
              </p>
            </div>
          </div>
      </section>
        
        <section class="bg-dark">
  
          <div class="container">
            <p class="text-center text-light">Nos statistique</p>
            <h1 class="text-center text-white w-lg-75 mx-auto fs-xl-6 fs-lg-4 fs-3">Découvrez les statistique de notre platforme</h1>
            <div class="row mt-5">
              <div class="col-md-4 col-sm-6 text-center">
                <h1 class="text-success fs-5 fs-md-6 fs-lg-7 fs-xl-9">120M</h1>
                <p class="text-light fs-2">Utilisateurs</p>
              </div>
              <div class="col-md-4 col-sm-6 text-center">
                <h1 class="text-success fs-5 fs-md-6 fs-lg-7 fs-xl-9">10.000</h1>
                <p class="text-light fs-2">Retour positive</p>
              </div>
              <div class="col-md-4 col-sm-6 text-center">
                <h1 class="text-success fs-5 fs-md-6 fs-lg-7 fs-xl-9">76%</h1>
                <p class="text-light fs-2">Prodéctivité</p>
              </div>
            </div>
          </div>
          <!-- end of .container-->
  
        </section>
        
        <section class="bg-light">
  
          <div class="container">
            <div class="px-xl-8 px-md-5 px-3">
              <p class="text-reset fs-1">Nos valeurs</p>
              <h1 class="text-dark fs-lg-6 fs-md-4 fs-3 my-lg-4 my-3">Things in we believe</h1>
              <p class="text-reset w-lg-75 fs-1">
                L'Innovation représnete une poursuite de nouvelles idées et technologies pour des solutions informatiques modernes.
                Ainsi que la Qualité est une adhésion à des normes élevées pour des logiciels fiables et performants.
                Note Collaboration est le travail d'équipe pour résoudre les défis et offrir des solutions efficaces.</p>
              <div class="row mt-5">
                <div class="col-md-3"><img class="img-fluid" src="{% static 'assets/img/values/1.png' %}" alt="" /></div>
                <div class="col-md-9 mt-2 mb-md-0">
                  <h1 class="text-dark fs-2 fs-lg-3 my-2">Innovation</h1>
                  <p class="text-reset fs-1">L'innovation est souvent une valeur clé dans le domaine du développement informatique. Les entreprises axées sur l'innovation encouragent leurs équipes à rechercher de nouvelles idées, à explorer de nouvelles technologies et à trouver des solutions novatrices aux problèmes. 
                   </p>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-md-3"><img class="img-fluid" src="{% static 'assets/img/values/2.png' %}" alt="" /></div>
                <div class="col-md-9 mt-2 mb-md-0">
                  <h1 class="text-dark fs-2 fs-lg-3 my-2">Qualité</h1>
                  <p class="text-reset fs-1">La qualité est essentielle dans le développement informatique pour assurer que les logiciels et les applications créés répondent aux normes élevées de performance, de fiabilité et de sécurité. 
                    </p>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-md-3"><img class="img-fluid" src="{% static 'assets/img/values/3.png' %}" alt="" /></div>
                <div class="col-md-9 mt-2 mb-md-0">
                  <h1 class="text-dark fs-2 fs-lg-3 my-2">Collaboration</h1>
                  <p class="text-reset fs-1">La collaboration est cruciale dans un domaine aussi interconnecté que le développement informatique. Les entreprises qui encouragent la collaboration créent un environnement où les équipes travaillent ensemble de manière transparente.</p>
                </div>
              </div>
            </div>
          </div>  
        </section>

      </main>
      
      
{% endblock content %}
{% include 'footer.html' %}

professeurs/templates/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <!-- ===============================================-->
            <!--    Document Title-->
            <!-- ===============================================-->
            <title>Ilyass | Simulateur de la paie</title>
            <!-- ===============================================-->
            <!--    Bootsrap 4-->
            <!-- ===============================================-->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
            <!-- ===============================================-->
            <!--    Bootsrap 5-->
            <!-- ===============================================-->
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
            {% load static %}
            <!-- ===============================================-->
            <!--    Bootstrap5 icones-->
            <!-- ===============================================-->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
            <!-- ===============================================-->
            <!--    Favicons-->
            <!-- ===============================================-->
            <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/img/favicons/apple-touch-icon.png' %}">
            <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicons/favicon-32x32.png' %}">
            <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicons/favicon-16x16.png' %}">
            <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicons/favicon.ico' %}">
            <link rel="manifest" href="{% static 'assets/img/favicons/manifest.json' %}">
            <meta name="msapplication-TileImage" content="assets/img/favicons/mstile-150x150.png">
            <meta name="theme-color" content="#ffffff">
            <!-- ===============================================-->
            <!--    Stylesheets-->
            <!-- ===============================================-->
            <link rel="preconnect" href="https://fonts.gstatic.com">
            <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700&amp;display=swap" rel="stylesheet">
            <link href="{% static 'vendors/prism/prism.css' %}" rel="stylesheet">
            <link href="{% static 'vendors/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
            <link href="{% static 'assets/css/theme.css' %}" rel="stylesheet" />
            <link href="{% static 'assets/css/user.css' %}" rel="stylesheet" />

            <!-- ===============================================-->
            <!--    JavaScripts-->
            <!-- ===============================================-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
            <script src="{% static 'vendors/popper/popper.min.js' %}"></script>
            <script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
            <script src="{% static 'vendors/anchorjs/anchor.min.js' %}"></script>
            <script src="{% static 'vendors/is/is.min.js' %}"></script>
            <script src="{%static 'vendors/fontawesome/all.min.js' %}"></script>
            <script src="{% static 'vendors/lodash/lodash.min.js' %}"></script>
            <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
            <script src="{% static 'vendors/prism/prism.js' %}"></script>
            <script src="{% static 'vendors/swiper/swiper-bundle.min.js' %}"></script>
            <script src="{% static 'assets/js/theme.js' %}"></script>

      </head>

<body>
        {% block content %}
        
        {% endblock content %}
</body>
</html>

professeurs/templates/enter_information.html
{% include 'base.html' %}
{% include 'navigation.html' %}


{% block content %}

    <h1>Enter Information</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    
{% endblock content %}
{% include 'footer.html' %}

professeurs/templates/index.html
{% include 'base.html' %}
{% include 'navigation.html' %}


{% block content %}

<h1>Simulateur de la paie</h1>

{% endblock content %}
{% include 'footer.html' %}

professeurs/templates/navigation.html
{% load static %}
{% load i18n %}
<style>
  .rounded-circle {
    width: 40px; /* Set the width and height to your desired circle size */
    height: 40px;
    text-align: center; /* Center the content horizontally */
    padding: 0; /* Remove any padding to fully utilize the circle dimensions */
    line-height: 40px; /* Center the content vertically */
}
</style>
<main class="main" id="top">
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark" data-navbar-on-scroll="data-navbar-on-scroll">
    
  
    <div class="container"><div class="container-md ms-2"><a class="navbar-brand me-1" href="{% url 'home' %}"><img src="{% static 'assets/img/4.png' %}" alt="" class="mx-auto"/>   Simulateur de la paie</a></div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa-solid fa-bars text-white fs-3"></i></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
              <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home' %}"> {% trans "Acceuil" %} </a></li>
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'about' %}"> {% trans "Propos" %} </a></li>
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'blogs' %}"> {% trans "Référence Réglementaire" %} </a></li>
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'selected-data' %}"> {% trans "Simulation de la paie" %} </a></li>
              {% if request.user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'accounts:profile' %}"> {% trans "Profile" %} </a></li>
              <li class="nav-item"><a class="nav-link btn btn-light text-black w-md-25 w-50 w-lg-100 " aria-current="page" href="{% url 'logout' %}"> {% trans "Déconexion" %} </a></li>
                 {% else %}
                 <li class="nav-item"><a class="nav-link btn btn-light text-black w-md-25 w-50 w-lg-100 " aria-current="page" href="{% url 'login' %}"> {% trans "Connexion" %} </a></li>
                 <li class="nav-item"><a class="nav-link btn btn-light text-black w-md-25 w-50 w-lg-100 ms-2" aria-current="page" href="{% url 'accounts:signup' %}"> {% trans "S'inscrire " %}</a></li>
              {% endif %}
             <!--Lang-->
           <!-- <div class="btn-group ms-3">
                  <button type="button" class="btn btn-info rounded-circle"><i class="bi bi-translate"></i></button>
                  <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split rounded-circle" data-bs-toggle="dropdown" aria-expanded="false">
                      <span class="visually-hidden">Toggle Dropdown</span>
                  </button>
                  <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Separated link</a></li>
                  </ul>
            </div>
            -->
            <i class="nav-item ms-3">
              <div class="container mt-0 nav-link btn btn-light text-black w-md-25 w-100 w-lg-100 p-2 h-10">
                  <form action="{% url 'set_language' %}" method="post" class="ms-3">
                      {% csrf_token %}
                      <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
                      <div class="row align-items-center g-1">
                          <div class="col-7">
                              <select name="language" class="form-select form-select-sm nav-link btn btn-light text-black w-md-25 w-50 w-lg-100" style="height: 1px;">
                                  {% get_current_language as LANGUAGE_CODE %}
                                  {% get_available_languages as LANGUAGES %}
                                  {% get_language_info_list for LANGUAGES as languages %}
                                  {% for language in languages %}
                                      <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                          {{ language.name_local }} ({{ language.code }})
                                      </option>
                                  {% endfor %}
                              </select>
                          </div>
                          <div class="col-5 text-end">
                              <button type="submit" class="btn btn-primary btn-sm px-2"><i class="bi bi-translate"></i></button>
                          </div>
                      </div>
                  </form>
              </div>
          </i>
          
        </ul>
      </div>
    </div>
  </nav>
  <div class="bg-dark"><img class="img-fluid position-absolute end-0" src="{% static 'assets/img/hero/hero-bg.png' %}" alt="" />
  
  

professeurs/templates/test.html
{% include 'base.html' %}
{% include 'navigation.html' %}

{% block content %}

<section class="g-dark text-center py-9">
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="submit">
    </form>
</section>
{% endblock content %}
{% include 'footer.html' %}